name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.CROSSFIT_OPEN_STREAMLIT_DOCKER }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/mon-app-streamlit:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/mon-app-streamlit:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mon-app-streamlit:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mon-app-streamlit:buildcache,mode=max

